# Generated by Django 3.0.6 on 2020-05-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='date_buy',
            field=models.DateTimeField(default='2020-05-22'),
        ),
    ]
