# Generated by Django 3.0.6 on 2020-05-22 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200522_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='date_buy',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
