# Generated by Django 3.0.6 on 2020-05-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200522_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='profit_loss',
            field=models.FloatField(default=0),
        ),
    ]
