# Generated by Django 3.0.6 on 2020-05-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_history_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='history',
            name='username',
            field=models.CharField(default='admin', max_length=25),
        ),
        migrations.AddField(
            model_name='overview',
            name='username',
            field=models.CharField(default='admin', max_length=25),
        ),
    ]
